# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'google_signin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for google_signin

  target 'google_signinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
